# Generated by Django 5.0.1 on 2025-04-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0003_aboutsection_aboutsectionm_service_servicem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='aboutsectionm',
            name='cv',
        ),
    ]
